Домашняя работа №1 Данилов Михаил
nskomega/FocusStartHomeworks pull request #4
Opened 2020-10-19 13:14 UTC by nskomega

2020-10-19 14:16 UTC, korshunigor commented
Задание принято на проверку

2020-10-21 13:54 UTC, Jinfaa commented on FocusStartHomeworks/Model/Car.swift
> +    case none = "none"
не нужно указывать значение в таком случае, мы можем извлечь значение через rawValue

2020-10-21 13:55 UTC, Jinfaa commented on FocusStartHomeworks/Model/Car.swift
> +class Car{
нужно использовать сткрутуру

2020-10-21 13:57 UTC, Jinfaa commented on FocusStartHomeworks/Model/Car.swift
> +    var manufacturer: String = ""
Дефолтные значения не нужно указывать, мы их назначим в конструкторе

2020-10-21 13:59 UTC, Jinfaa commented on FocusStartHomeworks/Controller/EditCarViewController.swift
> +    var typs:[String] = ["Выберите тип кузова", Body.none.rawValue, Body.jeep.rawValue, Body.sedan.rawValue, Body.cupe.rawValue, Body.universal.rawValue]
Так как у enum тип string то мы можем опустить rawValue

2020-10-21 14:01 UTC, Jinfaa commented on FocusStartHomeworks/Controller/ViewController.swift
> +    var cars: [Car] = []
По хорошему тут нужно делать опциональным пропертю. А в нужном месте где идет обращение к его свойству например: cars.count, делать cars?.count ?? 0

2020-10-21 14:02 UTC, Jinfaa commented on FocusStartHomeworks/Controller/ViewController.swift
> +        tableView.reloadData()
Избыточно

2020-10-21 14:03 UTC, Jinfaa commented on FocusStartHomeworks/Model/Car.swift
> +    var body: Body?
Оно не может быть необязательным

2020-10-21 14:06 UTC, Jinfaa commented on FocusStartHomeworks/Controller/EditCarViewController.swift
> +        if selectType != .none {
все присвоения выше не иметю никакого смысла в случае не выполнения условия

2020-10-21 14:17 UTC, Jinfaa commented on FocusStartHomeworks/Controller/EditCarViewController.swift
> +        if let car = car {
с учетом того что мы не можем открыть этот экран через список, это не будет работать.

2020-10-21 14:19 UTC, Jinfaa commented on FocusStartHomeworks/Controller/ViewController.swift
> +        tableView.reloadData()
Это избыточно. Будет вызвано раз при запуске приложения.

2020-10-21 14:20 UTC, Jinfaa commented
Нет открытие экрана с деталями по авто. Есть какие-то зачатки в этом направлении, не более того.

2020-10-21 14:22 UTC, Jinfaa commented on FocusStartHomeworks/Controller/EditCarViewController.swift
> +    var typs:[String] = ["Выберите тип кузова", Body.none.rawValue, Body.jeep.rawValue, Body.sedan.rawValue, Body.cupe.rawValue, Body.universal.rawValue]
+ название не должно фигурировать в списке типов

2020-10-22 04:05 UTC, Jinfaa requested changes
Есть замечания

2020-10-23 13:07 UTC, Jinfaa commented
Изменения есть, но не по всем пунктам, выполню проверку после внесения всех изменений.

2020-10-25 15:05 UTC, Jinfaa commented on FocusStartHomeworks/Controller/EditCarViewController.swift
> +            for type in typs {
if let index = self.typs.firstIndex(of: car.body) {
                self.typePikerView.selectRow(index, inComponent: 0, animated: true)
                self.selectType = self.typs[index]
            }

2020-10-25 15:07 UTC, Jinfaa commented on FocusStartHomeworks/Controller/ViewController.swift
> +                for car in cars {
Тут можно использовать .first

2020-10-25 15:07 UTC, Jinfaa commented on FocusStartHomeworks/Controller/ViewController.swift
> +        if let selectType = Body(rawValue: typs[row].rawValue), let cars = cars {
Используй guard

2020-10-25 15:09 UTC, Jinfaa commented on FocusStartHomeworks/Model/Car.swift
>  struct Car {
Не все свойства являются обязательными

2020-10-25 15:11 UTC, Jinfaa commented on FocusStartHomeworks/Controller/ViewController.swift
> +        tableView.reloadData()
Почему обновление представления идет перед обновлением carsFilter?

2020-10-25 15:12 UTC, Jinfaa requested changes
Требуется доработка

2020-10-27 13:56 UTC, Jinfaa approved these changes

2020-10-27 14:01 UTC, merged